// src/components/BackgroundVideo.vue
<script setup>
import { computed, onMounted, ref, useAttrs } from 'vue'

defineOptions({ inheritAttrs: false })
const props = defineProps({
  media: { type: Object, required: true },
  videoId: { type: String, default: undefined },
})
const attrs = useAttrs()
const video = ref(null)
const sourceList = computed(() => props.media.sources.map(source => source.src).join(','))
const posterStyle = computed(() => ({ backgroundImage: `url("${props.media.poster}")` }))

onMounted(() => {
  if (!video.value) return
  video.value.muted = true
  video.value.playsInline = true
  video.value.play().catch(() => {})
})
</script>

<template>
  <div
    v-bind="attrs"
    :data-poster-url="media.poster"
    :data-video-urls="sourceList"
    data-autoplay="true"
    data-loop="true"
  >
    <video
      :id="videoId"
      ref="video"
      autoplay
      loop
      muted
      playsinline
      :style="posterStyle"
      data-object-fit="cover"
    >
      <source v-for="source in media.sources" :key="source.src" :src="source.src" :type="source.type" />
    </video>
    <slot />
  </div>
</template>

// src/components/BackgroundVideo.jsx
import { useEffect, useRef } from 'react'

export default function BackgroundVideo({ media, videoId, children, ...rest }) {
  const videoRef = useRef(null)
  const sourceList = media.sources.map((source) => source.src).join(',')
  const posterStyle = { backgroundImage: `url("${media.poster}")` }

  useEffect(() => {
    const video = videoRef.current
    if (!video) return
    video.muted = true
    video.playsInline = true
    video.play().catch(() => {})
  }, [])

  return (
    <div
      {...rest}
      data-poster-url={media.poster}
      data-video-urls={sourceList}
      data-autoplay="true"
      data-loop="true"
    >
      <video
        id={videoId}
        ref={videoRef}
        autoPlay
        loop
        muted
        playsInline
        style={posterStyle}
        data-object-fit="cover"
      >
        {media.sources.map((source) => (
          <source key={source.src} src={source.src} type={source.type} />
        ))}
      </video>
      {children}
    </div>
  )
}
