// src/components/DesktopExperience.vue
<script setup>
import AppLink from './AppLink.vue'
import BackgroundVideo from './BackgroundVideo.vue'
import ClientList from './ClientList.vue'
import KitSignup from './KitSignup.vue'
import LogoCarousel from './LogoCarousel.vue'
import ManagerCard from './ManagerCard.vue'
import MerchEmptyState from './MerchEmptyState.vue'
import ResponsiveImage from './ResponsiveImage.vue'
import SectionHeading from './SectionHeading.vue'
import ShowEmptyState from './ShowEmptyState.vue'
import SocialLinks from './SocialLinks.vue'
import TextCta from './TextCta.vue'
import TopPickRelease from './TopPickRelease.vue'

defineProps({ content: { type: Object, required: true } })
</script>

<template>
  <div class="site site--desktop">
    <div class="desktop-flow">
      <BackgroundVideo
        :media="content.sections.hero.media.desktop"
        video-id="desktop-hero-video"
        class="background-media background-media--desktop-hero"
      >
        <SectionHeading
          :heading="content.sections.hero.heading"
          wrapper-class="display-heading--desktop-hero"
          title-class="heading-title--desktop-hero"
        />
        <div class="text-cta text-cta--desktop-hero">
          <ResponsiveImage :image="content.shared.texture" class="text-cta__texture" loading="lazy" />
          <AppLink :link="content.sections.hero.cta" class="text-cta__label" />
        </div>
        <ResponsiveImage :image="content.shared.arrow" class="text-cta__arrow" loading="lazy" />
        <SocialLinks :links="content.social_links" />
      </BackgroundVideo>

      <div class="section section--content">
        <SectionHeading
          :heading="content.sections.top_pick.heading"
          wrapper-class="display-heading--about"
          title-class="heading-title--about"
        />
        <TopPickRelease :release="content.sections.top_pick" variant="desktop" />

        <div id="w-node-_979f9f33-1dd2-e54e-b449-3b056707e4bf-0e0f149c" class="feature-block feature-block--why">
          <div class="content-block">
            <SectionHeading
              :heading="content.sections.upcoming_shows.heading"
              wrapper-class="display-heading--feature"
              title-class="heading-title--why"
            />
            <ShowEmptyState
              v-if="content.sections.upcoming_shows.items.length === 0"
              :copy="content.sections.upcoming_shows.copy"
            />
            <template v-else>
              <p class="body-copy body-copy--why">{{ content.sections.upcoming_shows.copy }}</p>
              <ClientList :items="content.sections.upcoming_shows.items" variant="desktop" />
            </template>
          </div>
        </div>

        <SectionHeading
          :heading="content.sections.booking.heading"
          wrapper-class="display-heading--feature"
          title-class="heading-title--feature"
        />
        <ManagerCard :manager="content.sections.booking.manager" />
      </div>

      <div class="section section--content">
        <div class="split-layout split-layout--studios">
          <div id="w-node-cd26b41e-3f3f-3433-26a8-674c93219bcc-0e0f149c" class="split-layout__content">
            <div class="content-block">
              <SectionHeading
                :heading="content.sections.merch.heading"
                wrapper-class="display-heading--feature"
                title-class="heading-title--feature"
              />
              <MerchEmptyState
                v-if="content.sections.merch.items.length === 0"
                :copy="content.sections.merch.copy"
                :cta="content.sections.merch.cta"
              />
              <template v-else>
                <p class="body-copy body-copy--studios">{{ content.sections.merch.copy }}</p>
                <TextCta
                  :cta="content.sections.merch.cta"
                  :arrow="content.shared.arrow"
                  wrapper-class="text-cta--inline"
                />
              </template>
            </div>
          </div>
        </div>
        <LogoCarousel v-if="content.sections.merch.items.length > 0" :items="content.sections.merch.items" />
      </div>

      <div id="mailing-list" class="section section--clients">
        <div class="section__inner">
          <SectionHeading
            :heading="content.sections.newsletter.heading"
            wrapper-class="display-heading--section"
            title-class="heading-title--clients"
          />
          <KitSignup id-prefix="desktop-newsletter" />
          <div class="newsletter-footer">{{ content.footer.copyright }}</div>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/DesktopExperience.jsx
import AppLink from './AppLink.jsx'
import BackgroundVideo from './BackgroundVideo.jsx'
import ClientList from './ClientList.jsx'
import KitSignup from './KitSignup.jsx'
import LogoCarousel from './LogoCarousel.jsx'
import ManagerCard from './ManagerCard.jsx'
import MerchEmptyState from './MerchEmptyState.jsx'
import ResponsiveImage from './ResponsiveImage.jsx'
import SectionHeading from './SectionHeading.jsx'
import ShowEmptyState from './ShowEmptyState.jsx'
import SocialLinks from './SocialLinks.jsx'
import TextCta from './TextCta.jsx'
import TopPickRelease from './TopPickRelease.jsx'

export default function DesktopExperience({ content }) {
  const shows = content.sections.upcoming_shows
  const merch = content.sections.merch

  return (
    <div className="site site--desktop">
      <div className="desktop-flow">
        <BackgroundVideo
          media={content.sections.hero.media.desktop}
          videoId="desktop-hero-video"
          className="background-media background-media--desktop-hero"
        >
          <SectionHeading
            heading={content.sections.hero.heading}
            wrapperClass="display-heading--desktop-hero"
            titleClass="heading-title--desktop-hero"
          />
          <div className="text-cta text-cta--desktop-hero">
            <ResponsiveImage image={content.shared.texture} className="text-cta__texture" loading="lazy" />
            <AppLink link={content.sections.hero.cta} className="text-cta__label" />
          </div>
          <ResponsiveImage image={content.shared.arrow} className="text-cta__arrow" loading="lazy" />
          <SocialLinks links={content.social_links} />
        </BackgroundVideo>

        <div className="section section--content">
          <SectionHeading
            heading={content.sections.top_pick.heading}
            wrapperClass="display-heading--about"
            titleClass="heading-title--about"
          />
          <TopPickRelease release={content.sections.top_pick} variant="desktop" />

          <div id="w-node-_979f9f33-1dd2-e54e-b449-3b056707e4bf-0e0f149c" className="feature-block feature-block--why">
            <div className="content-block">
              <SectionHeading
                heading={shows.heading}
                wrapperClass="display-heading--feature"
                titleClass="heading-title--why"
              />
              {shows.items.length === 0 ? (
                <ShowEmptyState copy={shows.copy} />
              ) : (
                <>
                  <p className="body-copy body-copy--why">{shows.copy}</p>
                  <ClientList items={shows.items} variant="desktop" />
                </>
              )}
            </div>
          </div>

          <SectionHeading
            heading={content.sections.booking.heading}
            wrapperClass="display-heading--feature"
            titleClass="heading-title--feature"
          />
          <ManagerCard manager={content.sections.booking.manager} />
        </div>

        <div className="section section--content">
          <div className="split-layout split-layout--studios">
            <div id="w-node-cd26b41e-3f3f-3433-26a8-674c93219bcc-0e0f149c" className="split-layout__content">
              <div className="content-block">
                <SectionHeading
                  heading={merch.heading}
                  wrapperClass="display-heading--feature"
                  titleClass="heading-title--feature"
                />
                {merch.items.length === 0 ? (
                  <MerchEmptyState copy={merch.copy} cta={merch.cta} />
                ) : (
                  <>
                    <p className="body-copy body-copy--studios">{merch.copy}</p>
                    <TextCta
                      cta={merch.cta}
                      arrow={content.shared.arrow}
                      wrapperClass="text-cta--inline"
                    />
                  </>
                )}
              </div>
            </div>
          </div>
          {merch.items.length > 0 && <LogoCarousel items={merch.items} />}
        </div>

        <div id="mailing-list" className="section section--clients">
          <div className="section__inner">
            <SectionHeading
              heading={content.sections.newsletter.heading}
              wrapperClass="display-heading--section"
              titleClass="heading-title--clients"
            />
            <KitSignup idPrefix="desktop-newsletter" />
            <div className="newsletter-footer">{content.footer.copyright}</div>
          </div>
        </div>
      </div>
    </div>
  )
}
