// src/components/MobileExperience.vue
<script setup>
import AppLink from './AppLink.vue'
import BackgroundVideo from './BackgroundVideo.vue'
import ClientList from './ClientList.vue'
import KitSignup from './KitSignup.vue'
import LogoCarousel from './LogoCarousel.vue'
import ManagerCard from './ManagerCard.vue'
import MerchEmptyState from './MerchEmptyState.vue'
import MobileSlider from './MobileSlider.vue'
import ResponsiveImage from './ResponsiveImage.vue'
import SectionHeading from './SectionHeading.vue'
import ShowEmptyState from './ShowEmptyState.vue'
import SocialLinks from './SocialLinks.vue'
import TextCta from './TextCta.vue'
import TopPickRelease from './TopPickRelease.vue'

defineProps({ content: { type: Object, required: true } })
</script>

<template>
  <MobileSlider
    v-slot="{ slideAttributes }"
    :slide-count="6"
    :continuous="content.mobile.continuous_scroll"
    :dot-label="content.accessibility.slider_dot_label"
    :previous-label="content.accessibility.previous_slide_label"
    :next-label="content.accessibility.next_slide_label"
  >
    <div class="mobile-slide mobile-slide--hero" v-bind="slideAttributes(0)">
      <BackgroundVideo
        :media="content.sections.hero.media.mobile"
        video-id="mobile-hero-video"
        class="background-media background-media--mobile-hero"
      >
        <div class="mobile-slide__overlay">
          <div class="mobile-slide__inner">
            <SectionHeading
              :heading="content.sections.hero.heading"
              wrapper-class="display-heading--mobile-hero"
              title-class="heading-title--mobile-hero"
            />
            <div class="text-cta text-cta--mobile-hero">
              <ResponsiveImage :image="content.shared.arrow" class="text-cta__arrow" loading="lazy" />
              <AppLink :link="content.sections.hero.cta" class="text-cta__label" />
              <ResponsiveImage :image="content.shared.texture" class="text-cta__texture" loading="lazy" />
            </div>
          </div>
        </div>
      </BackgroundVideo>
      <SocialLinks :links="content.social_links" />
    </div>

    <div class="mobile-slide" v-bind="slideAttributes(1)">
      <div class="mobile-slide__content mobile-slide__content--middle mobile-slide__content--top-pick">
        <SectionHeading
          :heading="content.sections.top_pick.heading"
          wrapper-class="display-heading--stacked"
          title-class="heading-title--mobile-about"
        />
        <TopPickRelease :release="content.sections.top_pick" variant="mobile" />
      </div>
      <BackgroundVideo
        :media="content.sections.top_pick.mobile_media"
        video-id="mobile-about-video"
        class="background-media background-media--slide"
      />
    </div>

    <div class="mobile-slide" v-bind="slideAttributes(2)">
      <div class="mobile-slide__content mobile-slide__content--why">
        <SectionHeading
          :heading="content.sections.upcoming_shows.heading"
          wrapper-class="display-heading--mobile-why"
          title-class="heading-title--mobile-why"
        />
        <ShowEmptyState
          v-if="content.sections.upcoming_shows.items.length === 0"
          :copy="content.sections.upcoming_shows.copy"
        />
        <template v-else>
          <p class="body-copy body-copy--mobile-why">{{ content.sections.upcoming_shows.copy }}</p>
          <div class="scroll-panel">
            <ClientList :items="content.sections.upcoming_shows.items" variant="mobile" />
          </div>
        </template>
      </div>
      <BackgroundVideo
        :media="content.sections.upcoming_shows.mobile_media"
        video-id="mobile-why-video"
        class="background-media background-media--slide"
      />
    </div>

    <div class="mobile-slide" v-bind="slideAttributes(3)">
      <div class="mobile-slide__content mobile-slide__content--how">
        <SectionHeading
          :heading="content.sections.booking.heading"
          wrapper-class="display-heading--mobile-how"
          title-class="heading-title--mobile-how"
        />
        <ManagerCard :manager="content.sections.booking.manager" />
      </div>
      <BackgroundVideo
        :media="content.sections.booking.mobile_media"
        video-id="mobile-how-video"
        class="background-media background-media--slide"
      />
    </div>

    <div class="mobile-slide" v-bind="slideAttributes(4)">
      <div class="mobile-slide__content mobile-slide__content--middle mobile-slide__content--merch">
        <SectionHeading
          :heading="content.sections.merch.heading"
          wrapper-class="display-heading--mobile-studios"
          title-class="heading-title--mobile-studios"
        />
        <MerchEmptyState
          v-if="content.sections.merch.items.length === 0"
          :copy="content.sections.merch.copy"
          :cta="content.sections.merch.cta"
        />
        <template v-else>
          <p class="body-copy body-copy--mobile-studios">{{ content.sections.merch.copy }}</p>
          <LogoCarousel :items="content.sections.merch.items" />
          <TextCta
            :cta="content.sections.merch.cta"
            :arrow="content.shared.arrow"
            wrapper-class="text-cta--mobile"
          />
        </template>
      </div>
      <BackgroundVideo
        :media="content.sections.merch.mobile_media"
        video-id="mobile-studios-video"
        class="background-media background-media--slide"
      />
    </div>

    <div id="mailing-list" class="mobile-slide" v-bind="slideAttributes(5)">
      <div class="mobile-slide__content mobile-slide__content--newsletter">
        <div>
          <SectionHeading
            :heading="content.sections.newsletter.heading"
            wrapper-class="display-heading--mobile-clients"
            title-class="heading-title--mobile-clients"
          />
          <KitSignup id-prefix="mobile-newsletter" />
        </div>
        <div class="newsletter-footer">{{ content.footer.copyright }}</div>
      </div>
      <BackgroundVideo
        :media="content.sections.newsletter.mobile_media"
        video-id="mobile-newsletter-video"
        class="background-media background-media--slide"
      />
    </div>
  </MobileSlider>
</template>

// src/components/MobileExperience.jsx
import AppLink from './AppLink.jsx'
import BackgroundVideo from './BackgroundVideo.jsx'
import ClientList from './ClientList.jsx'
import KitSignup from './KitSignup.jsx'
import LogoCarousel from './LogoCarousel.jsx'
import ManagerCard from './ManagerCard.jsx'
import MerchEmptyState from './MerchEmptyState.jsx'
import MobileSlider from './MobileSlider.jsx'
import ResponsiveImage from './ResponsiveImage.jsx'
import SectionHeading from './SectionHeading.jsx'
import ShowEmptyState from './ShowEmptyState.jsx'
import SocialLinks from './SocialLinks.jsx'
import TextCta from './TextCta.jsx'
import TopPickRelease from './TopPickRelease.jsx'

export default function MobileExperience({ content }) {
  const shows = content.sections.upcoming_shows
  const merch = content.sections.merch

  return (
    <MobileSlider
      slideCount={6}
      continuous={content.mobile.continuous_scroll}
      dotLabel={content.accessibility.slider_dot_label}
      previousLabel={content.accessibility.previous_slide_label}
      nextLabel={content.accessibility.next_slide_label}
    >
      {(slideAttributes) => (
        <>
          <div className="mobile-slide mobile-slide--hero" {...slideAttributes(0)}>
            <BackgroundVideo
              media={content.sections.hero.media.mobile}
              videoId="mobile-hero-video"
              className="background-media background-media--mobile-hero"
            >
              <div className="mobile-slide__overlay">
                <div className="mobile-slide__inner">
                  <SectionHeading
                    heading={content.sections.hero.heading}
                    wrapperClass="display-heading--mobile-hero"
                    titleClass="heading-title--mobile-hero"
                  />
                  <div className="text-cta text-cta--mobile-hero">
                    <ResponsiveImage image={content.shared.arrow} className="text-cta__arrow" loading="lazy" />
                    <AppLink link={content.sections.hero.cta} className="text-cta__label" />
                  </div>
                </div>
              </div>
            </BackgroundVideo>
            <SocialLinks links={content.social_links} />
          </div>

          <div className="mobile-slide" {...slideAttributes(1)}>
            <div className="mobile-slide__content mobile-slide__content--middle mobile-slide__content--top-pick">
              <SectionHeading
                heading={content.sections.top_pick.heading}
                wrapperClass="display-heading--stacked"
                titleClass="heading-title--mobile-about"
              />
              <TopPickRelease release={content.sections.top_pick} variant="mobile" />
            </div>
            <BackgroundVideo
              media={content.sections.top_pick.mobile_media}
              videoId="mobile-about-video"
              className="background-media background-media--slide"
            />
          </div>

          <div className="mobile-slide" {...slideAttributes(2)}>
            <div className="mobile-slide__content mobile-slide__content--why">
              <SectionHeading
                heading={shows.heading}
                wrapperClass="display-heading--mobile-why"
                titleClass="heading-title--mobile-why"
              />
              {shows.items.length === 0 ? (
                <ShowEmptyState copy={shows.copy} />
              ) : (
                <>
                  <p className="body-copy body-copy--mobile-why">{shows.copy}</p>
                  <div className="scroll-panel">
                    <ClientList items={shows.items} variant="mobile" />
                  </div>
                </>
              )}
            </div>
            <BackgroundVideo
              media={shows.mobile_media}
              videoId="mobile-why-video"
              className="background-media background-media--slide"
            />
          </div>

          <div className="mobile-slide" {...slideAttributes(3)}>
            <div className="mobile-slide__content mobile-slide__content--how">
              <SectionHeading
                heading={content.sections.booking.heading}
                wrapperClass="display-heading--mobile-how"
                titleClass="heading-title--mobile-how"
              />
              <ManagerCard manager={content.sections.booking.manager} />
            </div>
            <BackgroundVideo
              media={content.sections.booking.mobile_media}
              videoId="mobile-how-video"
              className="background-media background-media--slide"
            />
          </div>

          <div className="mobile-slide" {...slideAttributes(4)}>
            <div className="mobile-slide__content mobile-slide__content--middle mobile-slide__content--merch">
              <SectionHeading
                heading={merch.heading}
                wrapperClass="display-heading--mobile-studios"
                titleClass="heading-title--mobile-studios"
              />
              {merch.items.length === 0 ? (
                <MerchEmptyState copy={merch.copy} cta={merch.cta} />
              ) : (
                <>
                  <p className="body-copy body-copy--mobile-studios">{merch.copy}</p>
                  <LogoCarousel items={merch.items} />
                  <TextCta
                    cta={merch.cta}
                    arrow={content.shared.arrow}
                    wrapperClass="text-cta--mobile"
                  />
                </>
              )}
            </div>
            <BackgroundVideo
              media={merch.mobile_media}
              videoId="mobile-studios-video"
              className="background-media background-media--slide"
            />
          </div>

          <div id="mailing-list" className="mobile-slide" {...slideAttributes(5)}>
            <div className="mobile-slide__content mobile-slide__content--newsletter">
              <div>
                <SectionHeading
                  heading={content.sections.newsletter.heading}
                  wrapperClass="display-heading--mobile-clients"
                  titleClass="heading-title--mobile-clients"
                />
                <KitSignup idPrefix="mobile-newsletter" />
              </div>
              <div className="newsletter-footer">{content.footer.copyright}</div>
            </div>
            <BackgroundVideo
              media={content.sections.newsletter.mobile_media}
              videoId="mobile-newsletter-video"
              className="background-media background-media--slide"
            />
          </div>
        </>
      )}
    </MobileSlider>
  )
}
