// src/components/NewsletterForm.jsx
import { Fragment, useState } from 'react'

export default function NewsletterForm({ content, idPrefix }) {
  const [submitted, setSubmitted] = useState(false)
  const fieldId = (field) => `${idPrefix}-${field.id}`

  function submit(event) {
    event.preventDefault()
    if (!event.currentTarget.reportValidity()) return
    setSubmitted(true)
  }

  return (
    <div className="newsletter-form">
      {!submitted ? (
        <form onSubmit={submit}>
          {content.fields.map((field) => (
            <Fragment key={field.id}>
              <label htmlFor={fieldId(field)} className="form-label">
                {field.label}
                {field.required && <span className="form-required"> {content.required_marker}</span>}
              </label>
              <input
                id={fieldId(field)}
                name={field.name}
                type={field.type}
                placeholder={field.placeholder}
                required={field.required}
                className="form-control"
              />
            </Fragment>
          ))}
          <input type="submit" data-wait={content.wait_label} className="form-submit" value={content.submit_label} />
        </form>
      ) : (
        <div className="form-status form-status--success" role="status">
          {content.success_message}
        </div>
      )}
    </div>
  )
}

// src/components/NewsletterForm.vue
<script setup>
import { ref } from 'vue'

const props = defineProps({
  content: { type: Object, required: true },
  idPrefix: { type: String, required: true },
})

const submitted = ref(false)

function fieldId(field) {
  return `${props.idPrefix}-${field.id}`
}

function submit(event) {
  if (!event.currentTarget.reportValidity()) return
  submitted.value = true
}
</script>

<template>
  <div class="newsletter-form">
    <form v-if="!submitted" @submit.prevent="submit">
      <template v-for="field in content.fields" :key="field.id">
        <label :for="fieldId(field)" class="form-label">
          {{ field.label }}<span v-if="field.required" class="form-required"> {{ content.required_marker }}</span>
        </label>
        <input
          :id="fieldId(field)"
          :name="field.name"
          :type="field.type"
          :placeholder="field.placeholder"
          :required="field.required"
          class="form-control"
        />
      </template>
      <input type="submit" :data-wait="content.wait_label" class="form-submit" :value="content.submit_label" />
    </form>
    <div v-else class="form-status form-status--success" role="status">
      {{ content.success_message }}
    </div>
  </div>
</template>
