// src/components/SocialLinks.vue
<script setup>
import AppLink from './AppLink.vue'
import ResponsiveImage from './ResponsiveImage.vue'

defineProps({ links: { type: Array, required: true } })
</script>

<template>
  <div class="social-links">
    <AppLink v-for="item in links" :key="item.id" :link="item" class="social-link">
      <ResponsiveImage :image="item.icon" class="social-icon" loading="lazy" />
    </AppLink>
  </div>
</template>

// src/components/SocialLinks.jsx
import AppLink from './AppLink.jsx'
import ResponsiveImage from './ResponsiveImage.jsx'

export default function SocialLinks({ links }) {
  return (
    <div className="social-links">
      {links.map((item) => (
        <AppLink key={item.id} link={item} className="social-link">
          <ResponsiveImage image={item.icon} className="social-icon" loading="lazy" />
        </AppLink>
      ))}
    </div>
  )
}
